### PR TITLE
Change to 2DO.pm & prevent script crashing

### PR DESCRIPTION
**Pull request by starflowerbracken**
(1) Replace defunct HYPEvents with new fork 2DO.pm
(2) Unicode characters were crashing the script. Added some lines to prevent this.

### CODE REVIEW

**Review by Outworldz — COMMENTED** [review]
Needs HTMLEntities instead of the regexes.  https://metacpan.org/pod/HTML::Entities

**Comment by starflowerbracken** [comment]
Thanks: useful comment. My attempt to resolve the unicode problem created worse ones so I have removed it for now. The regexes were a temporary working fix. I'll give this some time shortly to sort out the HTML entities :-)

**Comment by starflowerbracken** [comment]
Ok, I see that your original code did this. However, I was still getting unicode and tried to fix it, which actually worsened the problem, though the regexes removed stuff that HTML::Entities was obviously not catching, e.g. \XA0 and \X0A. What I don't know is if there will be anything else that slips through in the same way, i.e. other characters. It may be because there was no ampersand so HTML::Entities did not recognize these codes? The script is at least no longer crashing because of the regexes and the additional problems that I inadvertently created for the viewer have been reverted. So for now, on a practical level, I need to continue using the regexes so the script works. One of the main culprits (up until Christmas!) is the entry about a Victorian Christmas, which is still in the events and, if you look at it, may give you an insight into why HTML::Entities was not catching and decoding this particular piece of unicode?

**Comment by Outworldz** [comment]
\XA0 is actually sort of of valid HTML, = a Line Feed,which is \n.   It's obviously been escaped and should be converted to a <br> assuming there is  no 0xD0, or CR \r.   Regexes should be fine there.

I have not looked at unicode much, at all.  Will review my code and see what I can come up with. This is an extract of what is actually used on Hyperica on Outworldz and in Search.  And thanks a bunch for actually reporting on it!

~Fred

**Comment by Outworldz** [comment]
I know we do not want $description = unidecode(decode_entities($description)); - that does plain text translation of Unicode, the opposite of what we want. We need to keep it unicode and make sure it is UTF-8 .

**Comment by Outworldz** [comment]
I added a few lines, seems to work.

use Encode qw(encode_utf8);
Also test if a line is UTF, then convert it to Perls internal representation.
			if (!Encode::is_utf8($description))
			{
				$description = Encode::decode_utf8($description);
			}

Interestingly, you are correct about some regex's.  The x0A is needed to make a line feed into a <br>, even with HTML::Entities..  There are some places where a line feed is on the end, and not in the middle, at least, today.. (harmless)  One is in the middle of two strings today, so this works to split it into two HTML lines.

I added a breakpoint structure around the reg exps and combined the line feed into one with an /i ignore case switch to see if I can spot more oddities.  I do not believe two of them are needed, but left them ( harmless)

I needed to convert the Name, too, as ANTONY &amp; CLEOPTRA (sic) was in the name.

Note: this attachment is different - this is what I actually run on Outworldz. If you can use it and confirm and make patches
[!SearchEvents.zip](https://github.com/Outworldz/OpensimEvents/files/3935572/SearchEvents.zip)

, I would be thrilled to see another Pull request.

**Comment by starflowerbracken** [comment]
Are you aware that the in-world 2DO boards have gone white and show no
events? The script is still retrieving them so I don't quite understand
this. Is this liable to be a problem on my end? I have made no changes to
my setup as far as I know. Are you getting any problems?

Thanks,

Star

**Comment by starflowerbracken** [comment]
Hello,

I have now debugged this and I see that the problem is that there are no
current events and there is nothing wrong with the script.

Is there a problem maintaining this service? I notice that HYPEvents has a
notice of discontinuation and says that this is "outdated". I don't really
think it is though. The problem seems to be that we are relying on one
service that can break if the person's personal circumstances change...

All the best,


Star

**Pull request merged**
